CREATE TABLE User
(
  first_name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  UUID uuid NOT NULL,
  PRIMARY KEY (UUID)
);

CREATE TABLE Picture
(
  file_name VARCHAR(200) NOT NULL,
  ID INT NOT NULL,
  UUID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (UUID) REFERENCES User(UUID)
);

CREATE TABLE Invitation
(
  User_UUID INT NOT NULL,
  Event_ID INT NOT NULL,
  ID INT NOT NULL,
  UUID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (UUID) REFERENCES User(UUID)
);

CREATE TABLE Event
(
  ID INT NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Invitation(ID)
);

CREATE TABLE Registration
(
  ID INT NOT NULL,
  Event_ID INT NOT NULL,
  User_UUID INT NOT NULL,
  UUID INT NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (UUID) REFERENCES User(UUID),
  FOREIGN KEY (ID) REFERENCES Event(ID)
);