version: '3.5'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    environment:
      ROCKET_PORT: 80
      ROCKET_ADDRESS: "0.0.0.0"
      DB_USER: admin
      DB_PASSWORD: admin
    volumes:
      - ./src/:/docker/app/src/
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: justgo