version: '3.5'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    environment:
      ROCKET_PORT: 80
      ROCKET_ADDRESS: "0.0.0.0"
    volumes:
      - ./src/:/docker/app/src/